name: ðŸ–‹ï¸ Update package name

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_name:
    name: ðŸ–‹ï¸ Update package name
    runs-on: ubuntu-latest
    if: github.repository != 'libhal/libhal-target'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get target name from repo name
        id: target_name
        run: echo ${{ github.event.repository.name }} | sed -En "s/libhal-(.*)/target_name=\1/p" >> $GITHUB_ENV

      - name: Replace placeholder's with ${{ env.target_name }} within files
        run: find ./ -type f -not -path '*/\.*' -exec sed -i '' -e "s/__target__/${{ env.target_name }}/" {} \;

      - name: Replace placeholder's with ${{ env.target_name }} in file & folder names
        run: find ./ -type f -not -path '*/\.*' -exec rename "s/__target__/${{ env.target_name }}/" {} \;

      - name: Remove update_name.yml file
        run: rm .github/workflows/update_name.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
